[platformio]
default_envs = tx, rx
boards_dir = boards

[env]
platform = espressif32@6.13.0
framework = arduino
board = t3_s3_v1_x
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib@7.7.1
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DPR1_SERIAL_BAUD=921600
    -DPR1_LOG_BAUD=115200

[env:tx]
build_flags =
    ${env.build_flags}
    -DPR1_ROLE_TX=1

[env:rx]
build_flags =
    ${env.build_flags}
    -DPR1_ROLE_RX=1
