[platformio]
default_envs = safe

[env]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.arduino.memory_type = qio_qspi
board_build.partitions = huge_app.csv
build_flags =
    -Wall
    -Wextra
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1

[env:safe]
build_flags =
    ${env.build_flags}
    -D PR1_RF_ENABLED=0
